sonar.projectKey=rgkim-hsu_IOT-Smart_Farming
sonar.organization=rgkim-hsu
sonar.projectName=IOT Smart Farming (Java)
sonar.projectVersion=1.0

sonar.sources=IOT_Farm_V.2,ICEBURG_AccessControl_V.01,ICEBURG_Attendance
sonar.exclusions=**/Devices/**,**/Supportive Jar Files/**,**/Application Screenshots/**,**/*.jar,**/*.sql,**/*.pdf
sonar.java.source=8
sonar.java.binaries=.
